import type { AiAdapter } from "@/server/adapters/types";
import { renderTool } from "@/server/template/tool";

function titleCase(slug: string) {
  return slug
    .split(/[^a-z0-9]+/i)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

export class MockAiAdapter implements AiAdapter {
  async draftSpec(input: { prompt: string; templateType: string }) {
    const projectName = titleCase(input.prompt).slice(0, 48) || "Untitled Tool";
    const spec = [
      `# Spec: ${projectName}`,
      ``,
      `Template: ${input.templateType}`,
      `Goal: ${input.prompt}`,
      ``,
      `- Single-purpose tool UI (input -> result)`,
      `- Locus paywall gates the premium result`,
      `- One pricing tier, USDC`,
      `- Sunset after 72h without a transaction`
    ].join("\n");

    return {
      projectName,
      spec,
      architectSummary: `Decomposed prompt into a ${input.templateType} spec at ~80% confidence (decision-first, no clarifying loop).`
    };
  }

  async composeMicroSaas(input: {
    projectId: string;
    projectName: string;
    prompt: string;
    spec: string;
    templateType: string;
    baseUrl: string;
    amount: string;
    currency: string;
  }) {
    const html = renderTool({
      projectId: input.projectId,
      projectName: input.projectName,
      tagline: `${input.projectName}, on demand.`,
      inputLabel: "Your input",
      placeholder: `Describe what you want from "${input.prompt}"...`,
      ctaLabel: "Generate",
      resultText: `Generated by ${input.projectName}. This is the premium result for: ${input.prompt}.`,
      baseUrl: input.baseUrl,
      amount: input.amount,
      currency: input.currency
    });

    return {
      html,
      developerSummary: `Rendered the ${input.templateType} template for ${input.projectName} with the shared Locus paywall.`
    };
  }
}
