import type { AiAdapter } from "@/server/adapters/types";
import { renderTool } from "@/server/template/tool";
import { fetchRetry } from "@/server/adapters/http";

const OPENAI_URL = "https://api.openai.com/v1/chat/completions";

function env(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing ${name} (required for AI_DRIVER=real).`);
  }
  return value;
}

async function chatJson<T>(system: string, user: string): Promise<T> {
  const apiKey = env("OPENAI_API_KEY");
  const model = process.env.OPENAI_MODEL ?? "gpt-4o-mini";
  const maxTokens = Number(process.env.OPENAI_MAX_TOKENS ?? "1200");

  const response = await fetchRetry(OPENAI_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model,
      temperature: 0.4,
      max_tokens: maxTokens,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: system },
        { role: "user", content: user }
      ]
    })
  });

  if (!response.ok) {
    const detail = await response.text();
    throw new Error(`OpenAI ${response.status}: ${detail.slice(0, 300)}`);
  }

  const data = (await response.json()) as {
    choices?: { message?: { content?: string } }[];
  };
  const content = data.choices?.[0]?.message?.content;
  if (!content) {
    throw new Error("OpenAI returned an empty completion.");
  }
  return JSON.parse(content) as T;
}

export class RealAiAdapter implements AiAdapter {
  async draftSpec(input: { prompt: string; templateType: string }) {
    const result = await chatJson<{
      projectName?: string;
      spec?: string;
      architectSummary?: string;
    }>(
      "You are the Architect agent of an autonomous micro-SaaS foundry. " +
        "Decision-first: commit at ~80% confidence, never ask the user to clarify. " +
        'Respond as JSON: {"projectName": string, "spec": string, "architectSummary": string}. ' +
        "The spec must fit a single-purpose tool with a Locus USDC paywall and 72h sunset.",
      `Template type: ${input.templateType}\nUser prompt: ${input.prompt}`
    );

    return {
      projectName: (result.projectName ?? "Untitled Tool").slice(0, 64),
      spec: result.spec ?? "",
      architectSummary:
        result.architectSummary ?? "Spec drafted by the Architect agent."
    };
  }

  async composeMicroSaas(input: {
    projectId: string;
    projectName: string;
    prompt: string;
    spec: string;
    templateType: string;
    baseUrl: string;
    amount: string;
    currency: string;
  }) {
    const result = await chatJson<{
      tagline?: string;
      inputLabel?: string;
      placeholder?: string;
      ctaLabel?: string;
      resultText?: string;
    }>(
      "You are the Developer agent for a micro-SaaS foundry. You only write " +
        "the product COPY for a fixed single-purpose tool template (input -> " +
        "gated result with a Locus USDC paywall). Be concrete to the product. " +
        'Respond as JSON: {"tagline": string, "inputLabel": string, ' +
        '"placeholder": string, "ctaLabel": string, "resultText": string}.',
      `Product: ${input.projectName}\nPrompt: ${input.prompt}\nSpec:\n${input.spec}`
    );

    const html = renderTool({
      projectId: input.projectId,
      projectName: input.projectName,
      tagline: result.tagline ?? `${input.projectName}, on demand.`,
      inputLabel: result.inputLabel ?? "Your input",
      placeholder: result.placeholder ?? "Describe what you need...",
      ctaLabel: result.ctaLabel ?? "Generate",
      resultText:
        result.resultText ??
        `Premium result generated by ${input.projectName}.`,
      baseUrl: input.baseUrl,
      amount: input.amount,
      currency: input.currency
    });

    return {
      html,
      developerSummary: `Generated ${input.projectName} copy with the Developer agent and rendered the shared tool template.`
    };
  }
}
