import type { GitAdapter, TemplateFile } from "@/server/adapters/types";
import { fetchRetry } from "@/server/adapters/http";

const GH = "https://api.github.com";

function env(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`Missing ${name} (required for GIT_DRIVER=real).`);
  return value;
}

function headers() {
  return {
    Authorization: `Bearer ${env("GITHUB_TOKEN")}`,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    "Content-Type": "application/json"
  };
}

export class RealGitAdapter implements GitAdapter {
  async createRepository(input: { slug: string; name: string }) {
    const owner = env("GITHUB_OWNER");
    const ownerType =
      process.env.GITHUB_OWNER_TYPE === "org" ? "org" : "user";
    const createUrl =
      ownerType === "org" ? `${GH}/orgs/${owner}/repos` : `${GH}/user/repos`;
    let repo = input.slug.replace(/[^a-z0-9-]/g, "-").slice(0, 90) || "tool";

    for (let attempt = 0; attempt < 3; attempt += 1) {
      const res = await fetchRetry(createUrl, {
        method: "POST",
        headers: headers(),
        body: JSON.stringify({
          name: repo,
          description: `Generated by SaaS-Factory.ai: ${input.name}`,
          // Private by default; opt into public explicitly.
          private: process.env.GITHUB_REPO_PRIVATE !== "false",
          auto_init: true
        })
      });

      if (res.ok) {
        const data = (await res.json()) as {
          html_url: string;
          full_name: string;
        };
        return {
          repoUrl: data.html_url,
          externalRepoId: data.full_name
        };
      }

      if (res.status === 422) {
        // Name taken — add a short suffix and retry.
        repo = `${repo.slice(0, 80)}-${Math.random().toString(36).slice(2, 6)}`;
        continue;
      }

      throw new Error(
        `GitHub createRepo ${res.status}: ${(await res.text()).slice(0, 200)}`
      );
    }

    void owner;
    throw new Error("GitHub createRepo failed after retries.");
  }

  async pushFiles(input: {
    externalRepoId: string;
    files: TemplateFile[];
  }) {
    let lastSha = "";
    for (const file of input.files) {
      const path = file.path.replace(/^\/+/, "");
      const contentsUrl = `${GH}/repos/${input.externalRepoId}/contents/${path}`;

      // If the path already exists (e.g. auto_init README), GitHub requires
      // the blob sha to update it; otherwise PUT 422s.
      let sha: string | undefined;
      const existing = await fetchRetry(contentsUrl, { headers: headers() });
      if (existing.ok) {
        const meta = (await existing.json()) as { sha?: string };
        sha = meta.sha;
      }

      const res = await fetchRetry(contentsUrl, {
        method: "PUT",
        headers: headers(),
        body: JSON.stringify({
          message: `feat: add ${path}`,
          content: Buffer.from(file.contents, "utf8").toString("base64"),
          ...(sha ? { sha } : {})
        })
      });
      if (!res.ok) {
        throw new Error(
          `GitHub pushFile ${path} ${res.status}: ${(await res.text()).slice(0, 200)}`
        );
      }
      const data = (await res.json()) as { commit?: { sha?: string } };
      lastSha = data.commit?.sha ?? lastSha;
    }
    return { commitSha: lastSha };
  }

  async archiveRepository(input: { externalRepoId: string }) {
    const res = await fetchRetry(`${GH}/repos/${input.externalRepoId}`, {
      method: "PATCH",
      headers: headers(),
      body: JSON.stringify({ archived: true })
    });
    if (!res.ok && res.status !== 404) {
      throw new Error(`GitHub archive ${res.status}`);
    }
  }
}
